apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: encrypted
  annotations:
    storageclass.kubernetes.io/is-default-class: 'false'
parameters:
  encrypted: 'true'
  type: gp2
allowVolumeExpansion: true
provisioner: ebs.csi.aws.com
reclaimPolicy: Delete
volumeBindingMode: Immediate