apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: secret-key-provider
  namespace: default
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "SECRET_KEYYYa"
        objectType: "secretsmanager"
      - objectName: "is_database_hosta"
        objectType: "secretsmanager"
      - objectName: "is_database_usera"
        objectType: "secretsmanager"
      - objectName: "is_debuga"
        objectType: "secretsmanager"
      - objectName: "is_database_passworda"
        objectType: "secretsmanager"
      - objectName: "is_database_namea"
        objectType: "secretsmanager"
      - objectName: "is_database_porta"
        objectType: "secretsmanager"
      

